<a href="https://colab.research.google.com/github/zarfer007/Boekhouding/blob/main/Jaarafsluiting_2024_Cranes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Anthony Cranes 2024

# Packages

## Packages install

In [ ]:
pip install PyPDF2 pdfplumber tabula-py pandas

Collecting PyPDF2
  Downloading pypdf2-3.0.1-py3-none-any.whl.metadata (6.8 kB)
Collecting pdfplumber
  Downloading pdfplumber-0.11.6-py3-none-any.whl.metadata (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 kB 3.1 MB/s eta 0:00:00
Collecting tabula-py
  Downloading tabula_py-2.10.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Collecting pdfminer.six==20250327 (from pdfplumber)
  Downloading pdfminer_six-20250327-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: Pillow>=9.1 in /usr/local/lib/python3.11/dist-packages (from pdfplumber) (11.2.1)
Collecting pypdfium2>=4.18.0 (from pdfplumber)
  Downloading pypdfium2-4.30.1-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.2/48.2 kB 2.1 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from pdfminer.six==20250327->pdfplumber) (3.4.2)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.11/dist-packages (from pdfminer.six==20250327->pdfplumber) (43.0.3)
Requirement already satisfied: numpy>1.24.4 in /usr/local/lib/python3.11/dist-packages (from tabula-py) (2.0.2)
Requirement already satisfied: distro in /usr/local/lib/python3.11/dist-packages (from tabula-py) (1.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.11/dist-packages (from cryptography>=36.0.0->pdfminer.six==20250327->pdfplumber) (1.17.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20250327->pdfplumber) (2.22)
Downloading pypdf2-3.0.1-py3-none-any.whl (232 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 6.4 MB/s eta 0:00:00
Downloading pdfplumber-0.11.6-py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.2/60.2 kB 3.7 MB/s eta 0:00:00
Downloading pdfminer_six-20250327-py3-none-any.whl (5.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 20.2 MB/s eta 0:00:00
Downloading tabula_py-2.10.0-py3-none-any.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 35.1 MB/s eta 0:00:00
Downloading pypdfium2-4.30.1-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 19.1 MB/s eta 0:00:00
Installing collected packages: pypdfium2, PyPDF2, tabula-py, pdfminer.six, pdfplumber
Successfully installed PyPDF2-3.0.1 pdfminer.six-20250327 pdfplumber-0.11.6 pypdfium2-4.30.1 tabula-py-2.10.0

In [ ]:
pip install pymupdf # install via PyMuPDF

Collecting pymupdf
  Downloading pymupdf-1.26.0-cp39-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (3.4 kB)
Downloading pymupdf-1.26.0-cp39-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (24.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.1/24.1 MB 20.6 MB/s eta 0:00:00
Installing collected packages: pymupdf
Successfully installed pymupdf-1.26.0

In [ ]:
pip install tabula-py # install tabula-py and Java

Requirement already satisfied: tabula-py in /usr/local/lib/python3.11/dist-packages (2.10.0)
Requirement already satisfied: pandas>=0.25.3 in /usr/local/lib/python3.11/dist-packages (from tabula-py) (2.2.2)
Requirement already satisfied: numpy>1.24.4 in /usr/local/lib/python3.11/dist-packages (from tabula-py) (2.0.2)
Requirement already satisfied: distro in /usr/local/lib/python3.11/dist-packages (from tabula-py) (1.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.25.3->tabula-py) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.25.3->tabula-py) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.25.3->tabula-py) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=0.25.3->tabula-py) (1.17.0)

In [ ]:
!pip install PyPDF2 pdfplumber tabula-py camelot-py[cv]

Requirement already satisfied: PyPDF2 in /usr/local/lib/python3.11/dist-packages (3.0.1)
Requirement already satisfied: pdfplumber in /usr/local/lib/python3.11/dist-packages (0.11.6)
Requirement already satisfied: tabula-py in /usr/local/lib/python3.11/dist-packages (2.10.0)
Collecting camelot-py[cv]
  Downloading camelot_py-1.0.0-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: pdfminer.six==20250327 in /usr/local/lib/python3.11/dist-packages (from pdfplumber) (20250327)
Requirement already satisfied: Pillow>=9.1 in /usr/local/lib/python3.11/dist-packages (from pdfplumber) (11.2.1)
Requirement already satisfied: pypdfium2>=4.18.0 in /usr/local/lib/python3.11/dist-packages (from pdfplumber) (4.30.1)
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from pdfminer.six==20250327->pdfplumber) (3.4.2)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.11/dist-packages (from pdfminer.six==20250327->pdfplumber) (43.0.3)
Requirement already satisfied: pandas>=0.25.3 in /usr/local/lib/python3.11/dist-packages (from tabula-py) (2.2.2)
Requirement already satisfied: numpy>1.24.4 in /usr/local/lib/python3.11/dist-packages (from tabula-py) (2.0.2)
Requirement already satisfied: distro in /usr/local/lib/python3.11/dist-packages (from tabula-py) (1.9.0)
WARNING: camelot-py 1.0.0 does not provide the extra 'cv'
Requirement already satisfied: click>=8.0.1 in /usr/local/lib/python3.11/dist-packages (from camelot-py[cv]) (8.2.1)
Requirement already satisfied: chardet>=5.1.0 in /usr/local/lib/python3.11/dist-packages (from camelot-py[cv]) (5.2.0)
Requirement already satisfied: openpyxl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from camelot-py[cv]) (3.1.5)
Collecting pypdf<4.0,>=3.17 (from camelot-py[cv])
  Downloading pypdf-3.17.4-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: tabulate>=0.9.0 in /usr/local/lib/python3.11/dist-packages (from camelot-py[cv]) (0.9.0)
Requirement already satisfied: opencv-python-headless>=4.7.0.68 in /usr/local/lib/python3.11/dist-packages (from camelot-py[cv]) (4.11.0.86)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.11/dist-packages (from openpyxl>=3.1.0->camelot-py[cv]) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.25.3->tabula-py) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.25.3->tabula-py) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.25.3->tabula-py) (2025.2)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.11/dist-packages (from cryptography>=36.0.0->pdfminer.six==20250327->pdfplumber) (1.17.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=0.25.3->tabula-py) (1.17.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20250327->pdfplumber) (2.22)
Downloading pypdf-3.17.4-py3-none-any.whl (278 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.2/278.2 kB 6.1 MB/s eta 0:00:00
Downloading camelot_py-1.0.0-py3-none-any.whl (66 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.6/66.6 kB 5.3 MB/s eta 0:00:00
Installing collected packages: pypdf, camelot-py
Successfully installed camelot-py-1.0.0 pypdf-3.17.4

In [ ]:
pip install PyPDF2 pdfplumber tabula-py pandas

Requirement already satisfied: PyPDF2 in /usr/local/lib/python3.11/dist-packages (3.0.1)
Requirement already satisfied: pdfplumber in /usr/local/lib/python3.11/dist-packages (0.11.6)
Requirement already satisfied: tabula-py in /usr/local/lib/python3.11/dist-packages (2.10.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: pdfminer.six==20250327 in /usr/local/lib/python3.11/dist-packages (from pdfplumber) (20250327)
Requirement already satisfied: Pillow>=9.1 in /usr/local/lib/python3.11/dist-packages (from pdfplumber) (11.2.1)
Requirement already satisfied: pypdfium2>=4.18.0 in /usr/local/lib/python3.11/dist-packages (from pdfplumber) (4.30.1)
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from pdfminer.six==20250327->pdfplumber) (3.4.2)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.11/dist-packages (from pdfminer.six==20250327->pdfplumber) (43.0.3)
Requirement already satisfied: numpy>1.24.4 in /usr/local/lib/python3.11/dist-packages (from tabula-py) (2.0.2)
Requirement already satisfied: distro in /usr/local/lib/python3.11/dist-packages (from tabula-py) (1.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.11/dist-packages (from cryptography>=36.0.0->pdfminer.six==20250327->pdfplumber) (1.17.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20250327->pdfplumber) (2.22)

## Packages

In [ ]:
import fitz  # PyMuPDF
import pandas as pd
import tabula
import os

# Balans-resultaat

## Aj. 2022 (Bkj 2021)

In [ ]:
# File
x="/content/2022-20398737.pdf"
y= "temp_pages_4_to_6.pdf"

In [ ]:
# Optional: convert pages to a temporary PDF
def extract_pages_to_temp_pdf(input_pdf_path, output_pdf_path, start_page, end_page):
    doc = fitz.open(input_pdf_path)
    new_doc = fitz.open()
    for i in range(start_page - 1, end_page):  # 0-based indexing
        new_doc.insert_pdf(doc, from_page=i, to_page=i)
    new_doc.save(output_pdf_path)
    new_doc.close()

# Paths
input_pdf_path = x
temp_pdf_path = y


# Step 1: Extract pages 4 to 6 into a new PDF
extract_pages_to_temp_pdf(input_pdf_path, temp_pdf_path, 4, 6)

# Step 2: Use tabula to extract tables
# Note: This requires Java and tabula-py to be installed.
tables = tabula.read_pdf(temp_pdf_path, pages='all', multiple_tables=True)

# Step 3: Combine all tables into a single DataFrame
combined_df = pd.concat(tables, ignore_index=True)

# Optional: Clean up temporary file
os.remove(temp_pdf_path)

# Display the combined dataframe
print(combined_df)

WARNING:tabula.backend:Failed to import jpype dependencies. Fallback to subprocess.
WARNING:tabula.backend:No module named 'jpype'
WARNING:tabula.backend:Got stderr: May 30, 2025 8:55:08 PM org.apache.pdfbox.pdmodel.font.FileSystemFontProvider loadDiskCache
WARNING: New fonts found, font cache will be re-built
May 30, 2025 8:55:08 PM org.apache.pdfbox.pdmodel.font.FileSystemFontProvider <init>
WARNING: Building on-disk font cache, this may take a while
May 30, 2025 8:55:08 PM org.apache.pdfbox.pdmodel.font.FileSystemFontProvider <init>
WARNING: Finished building on-disk font cache, found 17 fonts
May 30, 2025 8:55:09 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for base font Symbol
May 30, 2025 8:55:09 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for base font ZapfDingbats

                         Unnamed: 0  Toel.  Codes   Boekjaar Vorig boekjaar  \
0                            ACTIVA    NaN    NaN        NaN            NaN
1                 OPRICHTINGSKOSTEN    NaN     20        NaN            NaN
2                      VASTE ACTIVA    NaN  21/28  6.337.109      4.770.730
3          Immateriële vaste activa  6.1.1     21        NaN            NaN
4            Materiële vaste activa  6.1.2  22/27  6.334.759      4.768.380
..                              ...    ...    ...        ...            ...
71                      Belastingen    NaN  450/3     71.003         88.511
72  Bezoldigingen en sociale lasten    NaN  454/9    112.663         71.003
73                 Overige schulden    NaN  47/48        NaN            NaN
74           Overlopende rekeningen    NaN  492/3      5.000            900
75            TOTAAL VAN DE PASSIVA    NaN  10/49  7.793.894      6.026.039

   Unnamed: 1
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
71        NaN
72        NaN
73        NaN
74        NaN
75        NaN

[76 rows x 6 columns]

In [ ]:
Balans = combined_df
Balans.rename(columns={'Unnamed: 0':'Rubriek'}, inplace=True)
Balans.rename(columns={'Vorig boekjaar':'Vorig_boekjaar'}, inplace=True)
Balans = Balans.drop('Unnamed: 1', axis=1)
#Balans = Balans.drop('Toel.', axis=1)
Balans = Balans.fillna(0)

In [ ]:
Balans_2022= Balans
Balans_2022

                            Rubriek  Toel.  Codes   Boekjaar Vorig_boekjaar
0                            ACTIVA      0      0          0              0
1                 OPRICHTINGSKOSTEN      0     20          0              0
2                      VASTE ACTIVA      0  21/28  6.337.109      4.770.730
3          Immateriële vaste activa  6.1.1     21          0              0
4            Materiële vaste activa  6.1.2  22/27  6.334.759      4.768.380
..                              ...    ...    ...        ...            ...
71                      Belastingen      0  450/3     71.003         88.511
72  Bezoldigingen en sociale lasten      0  454/9    112.663         71.003
73                 Overige schulden      0  47/48          0              0
74           Overlopende rekeningen      0  492/3      5.000            900
75            TOTAAL VAN DE PASSIVA      0  10/49  7.793.894      6.026.039

[76 rows x 5 columns]

In [ ]:
y= "temp_pages_7_to_8.pdf"

In [ ]:
# Optional: convert pages to a temporary PDF
def extract_pages_to_temp_pdf(input_pdf_path, output_pdf_path, start_page, end_page):
    doc = fitz.open(input_pdf_path)
    new_doc = fitz.open()
    for i in range(start_page - 1, end_page):  # 0-based indexing
        new_doc.insert_pdf(doc, from_page=i, to_page=i)
    new_doc.save(output_pdf_path)
    new_doc.close()

# Paths
input_pdf_path = x
temp_pdf_path = y


# Step 1: Extract pages 4 to 6 into a new PDF
extract_pages_to_temp_pdf(input_pdf_path, temp_pdf_path, 7, 8)

# Step 2: Use tabula to extract tables
# Note: This requires Java and tabula-py to be installed.
tables = tabula.read_pdf(temp_pdf_path, pages='all', multiple_tables=True)

# Step 3: Combine all tables into a single DataFrame
combined_df = pd.concat(tables, ignore_index=True)

# Optional: Clean up temporary file
os.remove(temp_pdf_path)

# Display the combined dataframe
print(combined_df)

WARNING:tabula.backend:Got stderr: May 30, 2025 8:55:17 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for base font Symbol
May 30, 2025 8:55:17 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for base font ZapfDingbats

                                           Unnamed: 0 Unnamed: 1  Toel.  \
0               Bedrijfsopbrengsten en bedrijfskosten        NaN    NaN
1                                          Brutomarge    (+)/(-)    NaN
2        Waarvan: niet-recurrente bedrijfsopbrengsten        NaN    NaN
3                                               Omzet        NaN    NaN
4   Handelsgoederen, grond- en hulpstoffen, dienst...        NaN    NaN
5                                                 NaN        NaN    NaN
6                                    diverse goederen        NaN    NaN
7         Bezoldigingen, sociale lasten en pensioenen    (+)/(-)    NaN
8   Afschrijvingen en waardeverminderingen op opri...        NaN    NaN
9                                                 NaN        NaN    NaN
10           op immateriële en materiële vaste activa        NaN    NaN
11  Waardeverminderingen op voorraden, op bestelli...        NaN    NaN
12  uitvoering en op handelsvorderingen: toevoegingen    (+)/(-)    NaN
13                                    (terugnemingen)        NaN    NaN
14  Voorzieningen voor risico's en kosten: toevoeg...        NaN    NaN
15                                                NaN    (+)/(-)    NaN
16                     (bestedingen en terugnemingen)        NaN    NaN
17                              Andere bedrijfskosten        NaN    NaN
18  Als herstructureringskosten geactiveerde bedri...        (-)    NaN
19                     Niet-recurrente bedrijfskosten        NaN    NaN
20                    Bedrijfswinst (Bedrijfsverlies)    (+)/(-)    NaN
21                             Financiële opbrengsten        NaN    6.4
22                  Recurrente financiële opbrengsten        NaN    NaN
23            Waarvan: kapitaal- en interestsubsidies        NaN    NaN
24             Niet-recurrente financiële opbrengsten        NaN    NaN
25                                  Financiële kosten        NaN    6.4
26                       Recurrente financiële kosten        NaN    NaN
27                  Niet-recurrente financiële kosten        NaN    NaN
28    Winst (Verlies) van het boekjaar vóór belasting    (+)/(-)    NaN
29         Onttrekking aan de uitgestelde belastingen        NaN    NaN
30        Overboeking naar de uitgestelde belastingen        NaN    NaN
31                       Belastingen op het resultaat    (+)/(-)    NaN
32                   Winst (Verlies) van het boekjaar    (+)/(-)    NaN
33         Onttrekking aan de belastingvrije reserves        NaN    NaN
34        Overboeking naar de belastingvrije reserves        NaN    NaN
35      Te bestemmen winst (verlies) van het boekjaar    (+)/(-)    NaN
36                       Te bestemmen winst (verlies)    (+)/(-)    NaN
37      Te bestemmen winst (verlies) van het boekjaar    (+)/(-)    NaN
38  Overgedragen winst (verlies) van het vorige bo...    (+)/(-)    NaN
39                 Onttrekking aan het eigen vermogen        NaN    NaN
40                  Toevoeging aan het eigen vermogen        NaN    NaN
41                                     aan de inbreng        NaN    NaN
42                          aan de wettelijke reserve        NaN    NaN
43                            aan de overige reserves        NaN    NaN
44                     Over te dragen winst (verlies)    (+)/(-)    NaN
45         Tussenkomst van de vennoten in het verlies        NaN    NaN
46                                 Uit te keren winst        NaN    NaN
47                          Vergoeding van de inbreng        NaN    NaN
48                        Bestuurders of zaakvoerders        NaN    NaN
49                                         Werknemers        NaN    NaN
50                              Andere rechthebbenden        NaN    NaN

     Codes   Boekjaar Vorig boekjaar
0      NaN        NaN            NaN
1     9900  2.589.318      2.017.610
2      76A     95.300         18.761
3       70        NaN            NaN
4      NaN        NaN            NaN
5    60/61        NaN            NaN
6      NaN        NaN            NaN
7       62  1.272.910        986.026
8      NaN        NaN            NaN
9      630    599.986        653.964
10     NaN        NaN            NaN
11     NaN        NaN            NaN
12   631/4      7.254          8.547
13     NaN        NaN            NaN
14     NaN        NaN            NaN
15   635/8        NaN            NaN
16     NaN        NaN            NaN
17   640/8     16.467         15.120
18     649        NaN            NaN
19     66A        NaN            NaN
20    9901    692.701        353.953
21  75/76B      6.600          5.600
22      75      6.600          5.600
23     753        NaN            NaN
24     76B        NaN            NaN
25  65/66B     91.267         82.749
26      65     91.267         82.749
27     66B        NaN            NaN
28    9903    608.034        276.804
29     780      6.175          6.018
30     680     18.870            NaN
31   67/77     33.588         56.111
32    9904    561.751        226.711
33     789     24.096         23.482
34     689     73.630            NaN
35    9905    512.217        250.193
36    9906  1.685.895      1.273.678
37  (9905)    512.217        250.193
38     14P  1.173.678      1.023.485
39   791/2        NaN            NaN
40   691/2    100.000        100.000
41     691        NaN            NaN
42    6920        NaN            NaN
43    6921    100.000        100.000
44    (14)  1.585.895      1.173.678
45     794        NaN            NaN
46   694/7        NaN            NaN
47     694        NaN            NaN
48     695        NaN            NaN
49     696        NaN            NaN
50     697        NaN            NaN

In [ ]:
Resultaat = combined_df
Resultaat.rename(columns={'Unnamed: 0':'Rubriek'}, inplace=True)
Resultaat.rename(columns={'Vorig boekjaar':'Vorig_boekjaar'}, inplace=True)
Resultaat = Resultaat.drop('Unnamed: 1', axis=1)
#Balans = Balans.drop('Toel.', axis=1)
Resultaat = Resultaat.fillna(0)

In [ ]:
Resultaat_2022= Resultaat
Resultaat_2022

,Rubriek,Toel.,Codes,Boekjaar,Vorig_boekjaar
0,Bedrijfsopbrengsten en bedrijfskosten,0.0,0,0,0
1,Brutomarge,0.0,9900,2.589.318,2.017.610
2,Waarvan: niet-recurrente bedrijfsopbrengsten,0.0,76A,95.300,18.761
3,Omzet,0.0,70,0,0
4,"Handelsgoederen, grond- en hulpstoffen, dienst...",0.0,0,0,0
5,0,0.0,60/61,0,0
6,diverse goederen,0.0,0,0,0
7,"Bezoldigingen, sociale lasten en pensioenen",0.0,62,1.272.910,986.026
8,Afschrijvingen en waardeverminderingen op opri...,0.0,0,0,0
9,0,0.0,630,599.986,653.964
10,op immateriële en materiële vaste activa,0.0,0,0,0
11,"Waardeverminderingen op voorraden, op bestelli...",0.0,0,0,0
12,uitvoering en op handelsvorderingen: toevoegingen,0.0,631/4,7.254,8.547
13,(terugnemingen),0.0,0,0,0
14,Voorzieningen voor risico's en kosten: toevoeg...,0.0,0,0,0
15,0,0.0,635/8,0,0
16,(bestedingen en terugnemingen),0.0,0,0,0
17,Andere bedrijfskosten,0.0,640/8,16.467,15.120
18,Als herstructureringskosten geactiveerde bedri...,0.0,649,0,0
19,Niet-recurrente bedrijfskosten,0.0,66A,0,0
20,Bedrijfswinst (Bedrijfsverlies),0.0,9901,692.701,353.953
21,Financiële opbrengsten,6.4,75/76B,6.600,5.600
22,Recurrente financiële opbrengsten,0.0,75,6.600,5.600
23,Waarvan: kapitaal- en interestsubsidies,0.0,753,0,0
24,Niet-recurrente financiële opbrengsten,0.0,76B,0,0
25,Financiële kosten,6.4,65/66B,91.267,82.749
26,Recurrente financiële kosten,0.0,65,91.267,82.749
27,Niet-recurrente financiële kosten,0.0,66B,0,0
28,Winst (Verlies) van het boekjaar vóór belasting,0.0,9903,608.034,276.804
29,Onttrekking aan de uitgestelde belastingen,0.0,780,6.175,6.018
30,Overboeking naar de uitgestelde belastingen,0.0,680,18.870,0
31,Belastingen op het resultaat,0.0,67/77,33.588,56.111
32,Winst (Verlies) van het boekjaar,0.0,9904,561.751,226.711
33,Onttrekking aan de belastingvrije reserves,0.0,789,24.096,23.482
34,Overboeking naar de belastingvrije reserves,0.0,689,73.630,0
35,Te bestemmen winst (verlies) van het boekjaar,0.0,9905,512.217,250.193
36,Te bestemmen winst (verlies),0.0,9906,1.685.895,1.273.678
37,Te bestemmen winst (verlies) van het boekjaar,0.0,(9905),512.217,250.193
38,Overgedragen winst (verlies) van het vorige bo...,0.0,14P,1.173.678,1.023.485
39,Onttrekking aan het eigen vermogen,0.0,791/2,0,0
40,Toevoeging aan het eigen vermogen,0.0,691/2,100.000,100.000
41,aan de inbreng,0.0,691,0,0
42,aan de wettelijke reserve,0.0,6920,0,0
43,aan de overige reserves,0.0,6921,100.000,100.000
44,Over te dragen winst (verlies),0.0,(14),1.585.895,1.173.678
45,Tussenkomst van de vennoten in het verlies,0.0,794,0,0
46,Uit te keren winst,0.0,694/7,0,0
47,Vergoeding van de inbreng,0.0,694,0,0
48,Bestuurders of zaakvoerders,0.0,695,0,0
49,Werknemers,0.0,696,0,0
50,Andere rechthebbenden,0.0,697,0,0

## Aj. 2023 (Bkj 2022)

In [ ]:
# File
x="/content/2023-00251618.pdf"
y= "temp_pages_4_to_6.pdf"

In [ ]:
# Optional: convert pages to a temporary PDF
def extract_pages_to_temp_pdf(input_pdf_path, output_pdf_path, start_page, end_page):
    doc = fitz.open(input_pdf_path)
    new_doc = fitz.open()
    for i in range(start_page - 1, end_page):  # 0-based indexing
        new_doc.insert_pdf(doc, from_page=i, to_page=i)
    new_doc.save(output_pdf_path)
    new_doc.close()

# Paths
input_pdf_path = x
temp_pdf_path = y


# Step 1: Extract pages 4 to 6 into a new PDF
extract_pages_to_temp_pdf(input_pdf_path, temp_pdf_path, 4, 6)

# Step 2: Use tabula to extract tables
# Note: This requires Java and tabula-py to be installed.
tables = tabula.read_pdf(temp_pdf_path, pages='all', multiple_tables=True)

# Step 3: Combine all tables into a single DataFrame
combined_df = pd.concat(tables, ignore_index=True)

# Optional: Clean up temporary file
os.remove(temp_pdf_path)

# Display the combined dataframe
print(combined_df)

WARNING:tabula.backend:Got stderr: May 30, 2025 8:55:23 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for base font Symbol
May 30, 2025 8:55:23 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for base font ZapfDingbats

                         Unnamed: 0  Toel.  Codes    Boekjaar Vorig boekjaar  \
0                            ACTIVA    NaN    NaN         NaN            NaN
1                 OPRICHTINGSKOSTEN    NaN     20         NaN            NaN
2                      VASTE ACTIVA    NaN  21/28   8.560.679      6.337.109
3          Immateriële vaste activa  6.1.1     21      21.000            NaN
4            Materiële vaste activa  6.1.2  22/27   8.538.273      6.334.759
..                              ...    ...    ...         ...            ...
71                      Belastingen    NaN  450/3      78.994         71.003
72  Bezoldigingen en sociale lasten    NaN  454/9     152.716        112.663
73                 Overige schulden    NaN  47/48       3.756            NaN
74           Overlopende rekeningen    NaN  492/3       4.000          5.000
75            TOTAAL VAN DE PASSIVA    NaN  10/49  10.485.998      7.809.536

   Unnamed: 1
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
71        NaN
72        NaN
73        NaN
74        NaN
75        NaN

[76 rows x 6 columns]

In [ ]:
Balans = combined_df
Balans.rename(columns={'Unnamed: 0':'Rubriek'}, inplace=True)
Balans.rename(columns={'Vorig boekjaar':'Vorig_boekjaar'}, inplace=True)
Balans = Balans.drop('Unnamed: 1', axis=1)
#Balans = Balans.drop('Toel.', axis=1)
Balans = Balans.fillna(0)

In [ ]:
Balans_2023= Balans
Balans_2023

                            Rubriek  Toel.  Codes    Boekjaar Vorig_boekjaar
0                            ACTIVA      0      0           0              0
1                 OPRICHTINGSKOSTEN      0     20           0              0
2                      VASTE ACTIVA      0  21/28   8.560.679      6.337.109
3          Immateriële vaste activa  6.1.1     21      21.000              0
4            Materiële vaste activa  6.1.2  22/27   8.538.273      6.334.759
..                              ...    ...    ...         ...            ...
71                      Belastingen      0  450/3      78.994         71.003
72  Bezoldigingen en sociale lasten      0  454/9     152.716        112.663
73                 Overige schulden      0  47/48       3.756              0
74           Overlopende rekeningen      0  492/3       4.000          5.000
75            TOTAAL VAN DE PASSIVA      0  10/49  10.485.998      7.809.536

[76 rows x 5 columns]

In [ ]:
y= "temp_pages_7_to_8.pdf"

In [ ]:
# Optional: convert pages to a temporary PDF
def extract_pages_to_temp_pdf(input_pdf_path, output_pdf_path, start_page, end_page):
    doc = fitz.open(input_pdf_path)
    new_doc = fitz.open()
    for i in range(start_page - 1, end_page):  # 0-based indexing
        new_doc.insert_pdf(doc, from_page=i, to_page=i)
    new_doc.save(output_pdf_path)
    new_doc.close()

# Paths
input_pdf_path = x
temp_pdf_path = y


# Step 1: Extract pages 4 to 6 into a new PDF
extract_pages_to_temp_pdf(input_pdf_path, temp_pdf_path, 7, 8)

# Step 2: Use tabula to extract tables
# Note: This requires Java and tabula-py to be installed.
tables = tabula.read_pdf(temp_pdf_path, pages='all', multiple_tables=True)

# Step 3: Combine all tables into a single DataFrame
combined_df = pd.concat(tables, ignore_index=True)

# Optional: Clean up temporary file
os.remove(temp_pdf_path)

# Display the combined dataframe
print(combined_df)

WARNING:tabula.backend:Got stderr: May 30, 2025 8:55:26 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for base font Symbol
May 30, 2025 8:55:26 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for base font ZapfDingbats

                                           Unnamed: 0 Unnamed: 1  Toel.  \
0               Bedrijfsopbrengsten en bedrijfskosten        NaN    NaN
1                                          Brutomarge    (+)/(-)    NaN
2        Waarvan: niet-recurrente bedrijfsopbrengsten        NaN    NaN
3                                               Omzet        NaN    NaN
4   Handelsgoederen, grond- en hulpstoffen, dienst...        NaN    NaN
5                                                 NaN        NaN    NaN
6                                    diverse goederen        NaN    NaN
7         Bezoldigingen, sociale lasten en pensioenen    (+)/(-)    NaN
8   Afschrijvingen en waardeverminderingen op opri...        NaN    NaN
9                                                 NaN        NaN    NaN
10           op immateriële en materiële vaste activa        NaN    NaN
11  Waardeverminderingen op voorraden, op bestelli...        NaN    NaN
12  uitvoering en op handelsvorderingen: toevoegingen    (+)/(-)    NaN
13                                    (terugnemingen)        NaN    NaN
14  Voorzieningen voor risico's en kosten: toevoeg...        NaN    NaN
15                                                NaN    (+)/(-)    NaN
16                     (bestedingen en terugnemingen)        NaN    NaN
17                              Andere bedrijfskosten        NaN    NaN
18  Als herstructureringskosten geactiveerde bedri...        (-)    NaN
19                     Niet-recurrente bedrijfskosten        NaN    NaN
20                    Bedrijfswinst (Bedrijfsverlies)    (+)/(-)    NaN
21                             Financiële opbrengsten        NaN    6.4
22                  Recurrente financiële opbrengsten        NaN    NaN
23            Waarvan: kapitaal- en interestsubsidies        NaN    NaN
24             Niet-recurrente financiële opbrengsten        NaN    NaN
25                                  Financiële kosten        NaN    6.4
26                       Recurrente financiële kosten        NaN    NaN
27                  Niet-recurrente financiële kosten        NaN    NaN
28    Winst (Verlies) van het boekjaar vóór belasting    (+)/(-)    NaN
29         Onttrekking aan de uitgestelde belastingen        NaN    NaN
30        Overboeking naar de uitgestelde belastingen        NaN    NaN
31                       Belastingen op het resultaat    (+)/(-)    NaN
32                   Winst (Verlies) van het boekjaar    (+)/(-)    NaN
33         Onttrekking aan de belastingvrije reserves        NaN    NaN
34        Overboeking naar de belastingvrije reserves        NaN    NaN
35      Te bestemmen winst (verlies) van het boekjaar    (+)/(-)    NaN
36                       Te bestemmen winst (verlies)    (+)/(-)    NaN
37      Te bestemmen winst (verlies) van het boekjaar    (+)/(-)    NaN
38  Overgedragen winst (verlies) van het vorige bo...    (+)/(-)    NaN
39                 Onttrekking aan het eigen vermogen        NaN    NaN
40                  Toevoeging aan het eigen vermogen        NaN    NaN
41                                     aan de inbreng        NaN    NaN
42                          aan de wettelijke reserve        NaN    NaN
43                            aan de overige reserves        NaN    NaN
44                     Over te dragen winst (verlies)    (+)/(-)    NaN
45         Tussenkomst van de vennoten in het verlies        NaN    NaN
46                                 Uit te keren winst        NaN    NaN
47                          Vergoeding van de inbreng        NaN    NaN
48                        Bestuurders of zaakvoerders        NaN    NaN
49                                         Werknemers        NaN    NaN
50                              Andere rechthebbenden        NaN    NaN

     Codes   Boekjaar Vorig boekjaar
0      NaN        NaN            NaN
1     9900  3.216.880      2.589.318
2      76A    149.950         95.300
3       70        NaN            NaN
4      NaN        NaN            NaN
5    60/61        NaN            NaN
6      NaN        NaN            NaN
7       62  1.546.624      1.272.910
8      NaN        NaN            NaN
9      630    800.103        599.986
10     NaN        NaN            NaN
11     NaN        NaN            NaN
12   631/4        NaN          7.254
13     NaN        NaN            NaN
14     NaN        NaN            NaN
15   635/8        NaN            NaN
16     NaN        NaN            NaN
17   640/8     37.134         16.467
18     649        NaN            NaN
19     66A     49.785            NaN
20    9901    783.233        692.701
21  75/76B        400          6.600
22      75        400          6.600
23     753        NaN            NaN
24     76B        NaN            NaN
25  65/66B     98.674         91.267
26      65     98.021         91.267
27     66B        653            NaN
28    9903    684.959        608.034
29     780     38.750          6.175
30     680     23.500         18.870
31   67/77     22.326         33.588
32    9904    677.883        561.751
33     789        NaN         24.096
34     689     70.500         73.630
35    9905    607.383        512.217
36    9906  2.193.278      1.685.895
37  (9905)    607.383        512.217
38     14P  1.585.895      1.173.678
39   791/2        NaN            NaN
40   691/2    200.000        100.000
41     691    200.000            NaN
42    6920        NaN            NaN
43    6921        NaN        100.000
44    (14)  1.984.150      1.585.895
45     794        NaN            NaN
46   694/7      9.128            NaN
47     694        NaN            NaN
48     695        NaN            NaN
49     696      9.128            NaN
50     697        NaN            NaN

In [ ]:
Resultaat = combined_df
Resultaat.rename(columns={'Unnamed: 0':'Rubriek'}, inplace=True)
Resultaat.rename(columns={'Vorig boekjaar':'Vorig_boekjaar'}, inplace=True)
Resultaat = Resultaat.drop('Unnamed: 1', axis=1)
#Balans = Balans.drop('Toel.', axis=1)
Resultaat = Resultaat.fillna(0)

In [ ]:
Resultaat_2023= Resultaat
Resultaat_2023

,Rubriek,Toel.,Codes,Boekjaar,Vorig_boekjaar
0,Bedrijfsopbrengsten en bedrijfskosten,0.0,0,0,0
1,Brutomarge,0.0,9900,3.216.880,2.589.318
2,Waarvan: niet-recurrente bedrijfsopbrengsten,0.0,76A,149.950,95.300
3,Omzet,0.0,70,0,0
4,"Handelsgoederen, grond- en hulpstoffen, dienst...",0.0,0,0,0
5,0,0.0,60/61,0,0
6,diverse goederen,0.0,0,0,0
7,"Bezoldigingen, sociale lasten en pensioenen",0.0,62,1.546.624,1.272.910
8,Afschrijvingen en waardeverminderingen op opri...,0.0,0,0,0
9,0,0.0,630,800.103,599.986
10,op immateriële en materiële vaste activa,0.0,0,0,0
11,"Waardeverminderingen op voorraden, op bestelli...",0.0,0,0,0
12,uitvoering en op handelsvorderingen: toevoegingen,0.0,631/4,0,7.254
13,(terugnemingen),0.0,0,0,0
14,Voorzieningen voor risico's en kosten: toevoeg...,0.0,0,0,0
15,0,0.0,635/8,0,0
16,(bestedingen en terugnemingen),0.0,0,0,0
17,Andere bedrijfskosten,0.0,640/8,37.134,16.467
18,Als herstructureringskosten geactiveerde bedri...,0.0,649,0,0
19,Niet-recurrente bedrijfskosten,0.0,66A,49.785,0
20,Bedrijfswinst (Bedrijfsverlies),0.0,9901,783.233,692.701
21,Financiële opbrengsten,6.4,75/76B,400,6.600
22,Recurrente financiële opbrengsten,0.0,75,400,6.600
23,Waarvan: kapitaal- en interestsubsidies,0.0,753,0,0
24,Niet-recurrente financiële opbrengsten,0.0,76B,0,0
25,Financiële kosten,6.4,65/66B,98.674,91.267
26,Recurrente financiële kosten,0.0,65,98.021,91.267
27,Niet-recurrente financiële kosten,0.0,66B,653,0
28,Winst (Verlies) van het boekjaar vóór belasting,0.0,9903,684.959,608.034
29,Onttrekking aan de uitgestelde belastingen,0.0,780,38.750,6.175
30,Overboeking naar de uitgestelde belastingen,0.0,680,23.500,18.870
31,Belastingen op het resultaat,0.0,67/77,22.326,33.588
32,Winst (Verlies) van het boekjaar,0.0,9904,677.883,561.751
33,Onttrekking aan de belastingvrije reserves,0.0,789,0,24.096
34,Overboeking naar de belastingvrije reserves,0.0,689,70.500,73.630
35,Te bestemmen winst (verlies) van het boekjaar,0.0,9905,607.383,512.217
36,Te bestemmen winst (verlies),0.0,9906,2.193.278,1.685.895
37,Te bestemmen winst (verlies) van het boekjaar,0.0,(9905),607.383,512.217
38,Overgedragen winst (verlies) van het vorige bo...,0.0,14P,1.585.895,1.173.678
39,Onttrekking aan het eigen vermogen,0.0,791/2,0,0
40,Toevoeging aan het eigen vermogen,0.0,691/2,200.000,100.000
41,aan de inbreng,0.0,691,200.000,0
42,aan de wettelijke reserve,0.0,6920,0,0
43,aan de overige reserves,0.0,6921,0,100.000
44,Over te dragen winst (verlies),0.0,(14),1.984.150,1.585.895
45,Tussenkomst van de vennoten in het verlies,0.0,794,0,0
46,Uit te keren winst,0.0,694/7,9.128,0
47,Vergoeding van de inbreng,0.0,694,0,0
48,Bestuurders of zaakvoerders,0.0,695,0,0
49,Werknemers,0.0,696,9.128,0
50,Andere rechthebbenden,0.0,697,0,0

## Aj. 2024 (Bkj 2023)

In [ ]:
# File
x="/content/2024-00150415.pdf"
y= "temp_pages_4_to_6.pdf"

In [ ]:
# Optional: convert pages to a temporary PDF
def extract_pages_to_temp_pdf(input_pdf_path, output_pdf_path, start_page, end_page):
    doc = fitz.open(input_pdf_path)
    new_doc = fitz.open()
    for i in range(start_page - 1, end_page):  # 0-based indexing
        new_doc.insert_pdf(doc, from_page=i, to_page=i)
    new_doc.save(output_pdf_path)
    new_doc.close()

# Paths
input_pdf_path = x
temp_pdf_path = y


# Step 1: Extract pages 4 to 6 into a new PDF
extract_pages_to_temp_pdf(input_pdf_path, temp_pdf_path, 4, 6)

# Step 2: Use tabula to extract tables
# Note: This requires Java and tabula-py to be installed.
tables = tabula.read_pdf(temp_pdf_path, pages='all', multiple_tables=True)

# Step 3: Combine all tables into a single DataFrame
combined_df = pd.concat(tables, ignore_index=True)

# Optional: Clean up temporary file
os.remove(temp_pdf_path)

# Display the combined dataframe
print(combined_df)

WARNING:tabula.backend:Got stderr: May 30, 2025 8:55:30 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for base font Symbol
May 30, 2025 8:55:30 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for base font ZapfDingbats

                         Unnamed: 0  Toel.  Codes   Boekjaar Vorig boekjaar  \
0                            ACTIVA    NaN    NaN        NaN            NaN
1                 OPRICHTINGSKOSTEN    NaN     20        NaN            NaN
2                      VASTE ACTIVA    NaN  21/28  7.744.716      8.560.679
3          Immateriële vaste activa  6.1.1     21     16.164         21.000
4            Materiële vaste activa  6.1.2  22/27  7.727.147      8.538.273
..                              ...    ...    ...        ...            ...
71                      Belastingen    NaN  450/3     39.847         78.994
72  Bezoldigingen en sociale lasten    NaN  454/9    153.484        152.716
73                 Overige schulden    NaN  47/48     57.553          3.756
74           Overlopende rekeningen    NaN  492/3      2.500          4.000
75            TOTAAL VAN DE PASSIVA    NaN  10/49  9.296.654     10.485.998

   Unnamed: 1
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
..        ...
71        NaN
72        NaN
73        NaN
74        NaN
75        NaN

[76 rows x 6 columns]

In [ ]:
Balans = combined_df
Balans.rename(columns={'Unnamed: 0':'Rubriek'}, inplace=True)
Balans.rename(columns={'Vorig boekjaar':'Vorig_boekjaar'}, inplace=True)
Balans = Balans.drop('Unnamed: 1', axis=1)
#Balans = Balans.drop('Toel.', axis=1)
Balans = Balans.fillna(0)

In [ ]:
Balans_2024= Balans
Balans_2024

                            Rubriek  Toel.  Codes   Boekjaar Vorig_boekjaar
0                            ACTIVA      0      0          0              0
1                 OPRICHTINGSKOSTEN      0     20          0              0
2                      VASTE ACTIVA      0  21/28  7.744.716      8.560.679
3          Immateriële vaste activa  6.1.1     21     16.164         21.000
4            Materiële vaste activa  6.1.2  22/27  7.727.147      8.538.273
..                              ...    ...    ...        ...            ...
71                      Belastingen      0  450/3     39.847         78.994
72  Bezoldigingen en sociale lasten      0  454/9    153.484        152.716
73                 Overige schulden      0  47/48     57.553          3.756
74           Overlopende rekeningen      0  492/3      2.500          4.000
75            TOTAAL VAN DE PASSIVA      0  10/49  9.296.654     10.485.998

[76 rows x 5 columns]

In [ ]:
y= "temp_pages_7_to_8.pdf"

In [ ]:
# Optional: convert pages to a temporary PDF
def extract_pages_to_temp_pdf(input_pdf_path, output_pdf_path, start_page, end_page):
    doc = fitz.open(input_pdf_path)
    new_doc = fitz.open()
    for i in range(start_page - 1, end_page):  # 0-based indexing
        new_doc.insert_pdf(doc, from_page=i, to_page=i)
    new_doc.save(output_pdf_path)
    new_doc.close()

# Paths
input_pdf_path = x
temp_pdf_path = y


# Step 1: Extract pages 4 to 6 into a new PDF
extract_pages_to_temp_pdf(input_pdf_path, temp_pdf_path, 7, 8)

# Step 2: Use tabula to extract tables
# Note: This requires Java and tabula-py to be installed.
tables = tabula.read_pdf(temp_pdf_path, pages='all', multiple_tables=True)

# Step 3: Combine all tables into a single DataFrame
combined_df = pd.concat(tables, ignore_index=True)

# Optional: Clean up temporary file
os.remove(temp_pdf_path)

# Display the combined dataframe
print(combined_df)

WARNING:tabula.backend:Got stderr: May 30, 2025 8:55:35 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for base font Symbol
May 30, 2025 8:55:35 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for base font ZapfDingbats

                                           Unnamed: 0 Unnamed: 1  Toel.  \
0               Bedrijfsopbrengsten en bedrijfskosten        NaN    NaN
1                                          Brutomarge    (+)/(-)    NaN
2        Waarvan: niet-recurrente bedrijfsopbrengsten        NaN    NaN
3                                               Omzet        NaN    NaN
4   Handelsgoederen, grond- en hulpstoffen, dienst...        NaN    NaN
5                                                 NaN        NaN    NaN
6                                    diverse goederen        NaN    NaN
7         Bezoldigingen, sociale lasten en pensioenen    (+)/(-)    NaN
8   Afschrijvingen en waardeverminderingen op opri...        NaN    NaN
9                                                 NaN        NaN    NaN
10           op immateriële en materiële vaste activa        NaN    NaN
11  Waardeverminderingen op voorraden, op bestelli...        NaN    NaN
12  uitvoering en op handelsvorderingen: toevoegingen    (+)/(-)    NaN
13                                    (terugnemingen)        NaN    NaN
14  Voorzieningen voor risico's en kosten: toevoeg...        NaN    NaN
15                                                NaN    (+)/(-)    NaN
16                     (bestedingen en terugnemingen)        NaN    NaN
17                              Andere bedrijfskosten        NaN    NaN
18  Als herstructureringskosten geactiveerde bedri...        (-)    NaN
19                     Niet-recurrente bedrijfskosten        NaN    NaN
20                    Bedrijfswinst (Bedrijfsverlies)    (+)/(-)    NaN
21                             Financiële opbrengsten        NaN    6.4
22                  Recurrente financiële opbrengsten        NaN    NaN
23            Waarvan: kapitaal- en interestsubsidies        NaN    NaN
24             Niet-recurrente financiële opbrengsten        NaN    NaN
25                                  Financiële kosten        NaN    6.4
26                       Recurrente financiële kosten        NaN    NaN
27                  Niet-recurrente financiële kosten        NaN    NaN
28    Winst (Verlies) van het boekjaar vóór belasting    (+)/(-)    NaN
29         Onttrekking aan de uitgestelde belastingen        NaN    NaN
30        Overboeking naar de uitgestelde belastingen        NaN    NaN
31                       Belastingen op het resultaat    (+)/(-)    NaN
32                   Winst (Verlies) van het boekjaar    (+)/(-)    NaN
33         Onttrekking aan de belastingvrije reserves        NaN    NaN
34        Overboeking naar de belastingvrije reserves        NaN    NaN
35      Te bestemmen winst (verlies) van het boekjaar    (+)/(-)    NaN
36                       Te bestemmen winst (verlies)    (+)/(-)    NaN
37      Te bestemmen winst (verlies) van het boekjaar    (+)/(-)    NaN
38  Overgedragen winst (verlies) van het vorige bo...    (+)/(-)    NaN
39                 Onttrekking aan het eigen vermogen        NaN    NaN
40                  Toevoeging aan het eigen vermogen        NaN    NaN
41                                     aan de inbreng        NaN    NaN
42                          aan de wettelijke reserve        NaN    NaN
43                            aan de overige reserves        NaN    NaN
44                     Over te dragen winst (verlies)    (+)/(-)    NaN
45         Tussenkomst van de vennoten in het verlies        NaN    NaN
46                                 Uit te keren winst        NaN    NaN
47                          Vergoeding van de inbreng        NaN    NaN
48                        Bestuurders of zaakvoerders        NaN    NaN
49                                         Werknemers        NaN    NaN
50                              Andere rechthebbenden        NaN    NaN

     Codes   Boekjaar Vorig boekjaar
0      NaN        NaN            NaN
1     9900  3.522.965      3.216.880
2      76A    152.259        149.950
3       70        NaN            NaN
4      NaN        NaN            NaN
5    60/61        NaN            NaN
6      NaN        NaN            NaN
7       62  1.830.885      1.546.624
8      NaN        NaN            NaN
9      630  1.007.836        800.103
10     NaN        NaN            NaN
11     NaN        NaN            NaN
12   631/4        NaN            NaN
13     NaN        NaN            NaN
14     NaN        NaN            NaN
15   635/8        NaN            NaN
16     NaN        NaN            NaN
17   640/8     35.347         37.134
18     649        NaN            NaN
19     66A     20.400         49.785
20    9901    628.497        783.233
21  75/76B      1.618            400
22      75      1.618            400
23     753        NaN            NaN
24     76B        NaN            NaN
25  65/66B    144.007         98.674
26      65    144.007         98.021
27     66B          0            653
28    9903    486.107        684.959
29     780      9.863         38.750
30     680          0         23.500
31   67/77    123.064         22.326
32    9904    372.906        677.883
33     789     36.720              0
34     689    197.870         70.500
35    9905    211.756        607.383
36    9906  2.195.906      2.193.278
37  (9905)    211.756        607.383
38     14P  1.984.150      1.585.895
39   791/2        NaN            NaN
40   691/2          0        200.000
41     691        NaN            NaN
42    6920        NaN            NaN
43    6921          0        200.000
44    (14)  2.184.857      1.984.150
45     794        NaN            NaN
46   694/7     11.049          9.128
47     694        NaN            NaN
48     695        NaN            NaN
49     696     11.049          9.128
50     697        NaN            NaN

In [ ]:
Resultaat = combined_df
Resultaat.rename(columns={'Unnamed: 0':'Rubriek'}, inplace=True)
Resultaat.rename(columns={'Vorig boekjaar':'Vorig_boekjaar'}, inplace=True)
Resultaat = Resultaat.drop('Unnamed: 1', axis=1)
#Balans = Balans.drop('Toel.', axis=1)
Resultaat = Resultaat.fillna(0)

In [ ]:
Resultaat_2024= Resultaat
Resultaat_2024

,Rubriek,Toel.,Codes,Boekjaar,Vorig_boekjaar
0,Bedrijfsopbrengsten en bedrijfskosten,0.0,0,0,0
1,Brutomarge,0.0,9900,3.522.965,3.216.880
2,Waarvan: niet-recurrente bedrijfsopbrengsten,0.0,76A,152.259,149.950
3,Omzet,0.0,70,0,0
4,"Handelsgoederen, grond- en hulpstoffen, dienst...",0.0,0,0,0
5,0,0.0,60/61,0,0
6,diverse goederen,0.0,0,0,0
7,"Bezoldigingen, sociale lasten en pensioenen",0.0,62,1.830.885,1.546.624
8,Afschrijvingen en waardeverminderingen op opri...,0.0,0,0,0
9,0,0.0,630,1.007.836,800.103
10,op immateriële en materiële vaste activa,0.0,0,0,0
11,"Waardeverminderingen op voorraden, op bestelli...",0.0,0,0,0
12,uitvoering en op handelsvorderingen: toevoegingen,0.0,631/4,0,0
13,(terugnemingen),0.0,0,0,0
14,Voorzieningen voor risico's en kosten: toevoeg...,0.0,0,0,0
15,0,0.0,635/8,0,0
16,(bestedingen en terugnemingen),0.0,0,0,0
17,Andere bedrijfskosten,0.0,640/8,35.347,37.134
18,Als herstructureringskosten geactiveerde bedri...,0.0,649,0,0
19,Niet-recurrente bedrijfskosten,0.0,66A,20.400,49.785
20,Bedrijfswinst (Bedrijfsverlies),0.0,9901,628.497,783.233
21,Financiële opbrengsten,6.4,75/76B,1.618,400
22,Recurrente financiële opbrengsten,0.0,75,1.618,400
23,Waarvan: kapitaal- en interestsubsidies,0.0,753,0,0
24,Niet-recurrente financiële opbrengsten,0.0,76B,0,0
25,Financiële kosten,6.4,65/66B,144.007,98.674
26,Recurrente financiële kosten,0.0,65,144.007,98.021
27,Niet-recurrente financiële kosten,0.0,66B,0,653
28,Winst (Verlies) van het boekjaar vóór belasting,0.0,9903,486.107,684.959
29,Onttrekking aan de uitgestelde belastingen,0.0,780,9.863,38.750
30,Overboeking naar de uitgestelde belastingen,0.0,680,0,23.500
31,Belastingen op het resultaat,0.0,67/77,123.064,22.326
32,Winst (Verlies) van het boekjaar,0.0,9904,372.906,677.883
33,Onttrekking aan de belastingvrije reserves,0.0,789,36.720,0
34,Overboeking naar de belastingvrije reserves,0.0,689,197.870,70.500
35,Te bestemmen winst (verlies) van het boekjaar,0.0,9905,211.756,607.383
36,Te bestemmen winst (verlies),0.0,9906,2.195.906,2.193.278
37,Te bestemmen winst (verlies) van het boekjaar,0.0,(9905),211.756,607.383
38,Overgedragen winst (verlies) van het vorige bo...,0.0,14P,1.984.150,1.585.895
39,Onttrekking aan het eigen vermogen,0.0,791/2,0,0
40,Toevoeging aan het eigen vermogen,0.0,691/2,0,200.000
41,aan de inbreng,0.0,691,0,0
42,aan de wettelijke reserve,0.0,6920,0,0
43,aan de overige reserves,0.0,6921,0,200.000
44,Over te dragen winst (verlies),0.0,(14),2.184.857,1.984.150
45,Tussenkomst van de vennoten in het verlies,0.0,794,0,0
46,Uit te keren winst,0.0,694/7,11.049,9.128
47,Vergoeding van de inbreng,0.0,694,0,0
48,Bestuurders of zaakvoerders,0.0,695,0,0
49,Werknemers,0.0,696,11.049,9.128
50,Andere rechthebbenden,0.0,697,0,0

In [ ]:
Balans_2022.to_csv('Balans_2022.csv', index=False)
Balans_2023.to_csv('Balans_2023.csv', index=False)
Balans_2024.to_csv('Balans_2024.csv', index=False)
Resultaat_2022.to_csv('Resultaat_2022.csv', index=False)
Resultaat.to_csv('Resultaat_2023.csv', index=False)
Resultaat.to_csv('Resultaat_2024.csv', index=False)

## Boekjaren samevoegen

In [ ]:
# Dropping Toelichting

Balans_2022 = Balans_2022.drop('Toel.', axis=1)
Balans_2023 = Balans_2023.drop('Toel.', axis=1)
Balans_2024 = Balans_2024.drop('Toel.', axis=1)
Resultaat_2022 = Resultaat_2022.drop('Toel.', axis=1)
Resultaat_2023 = Resultaat_2023.drop('Toel.', axis=1)
Resultaat_2024 = Resultaat_2024.drop('Toel.', axis=1)

In [ ]:
# Dropping Toelichting
Balans_2022 = Balans_2022.drop('Codes', axis=1)
Balans_2023 = Balans_2023.drop('Codes', axis=1)
Resultaat_2022 = Resultaat_2022.drop('Codes', axis=1)
Resultaat_2023 = Resultaat_2023.drop('Codes', axis=1)

In [ ]:
# Dropping Vorig_boekjaar van 2024 en 2023
Balans_2023 = Balans_2023.drop('Vorig_boekjaar', axis=1)
Balans_2024 = Balans_2024.drop('Vorig_boekjaar', axis=1)
Resultaat_2023 = Resultaat_2023.drop('Vorig_boekjaar', axis=1)
Resultaat_2024 = Resultaat_2024.drop('Vorig_boekjaar', axis=1)

In [ ]:
Balans = pd.merge(Balans_2024, Balans_2023, on='Rubriek', suffixes=('_2024', '_2023'))
Balans = pd.merge(Balans, Balans_2022, on='Rubriek')
Balans.rename(columns={'Boekjaar':'Boekjaar_2022'}, inplace=True)
Balans.rename(columns={'Vorig_boekjaar':'Boekjaar_2021'}, inplace=True)
#Balans.drop_duplicates()
Balans

,Rubriek,Codes,Boekjaar_2024,Boekjaar_2023,Boekjaar_2022,Boekjaar_2021
0,ACTIVA,0,0,0,0,0
1,OPRICHTINGSKOSTEN,20,0,0,0,0
2,VASTE ACTIVA,21/28,7.744.716,8.560.679,6.337.109,4.770.730
3,Immateriële vaste activa,21,16.164,21.000,0,0
4,Materiële vaste activa,22/27,7.727.147,8.538.273,6.334.759,4.768.380
...,...,...,...,...,...,...
125,Overlopende rekeningen,492/3,2.500,95.981,25.979,17.874
126,Overlopende rekeningen,492/3,2.500,95.981,5.000,900
127,Overlopende rekeningen,492/3,2.500,4.000,25.979,17.874
128,Overlopende rekeningen,492/3,2.500,4.000,5.000,900
129,TOTAAL VAN DE PASSIVA,10/49,9.296.654,10.485.998,7.793.894,6.026.039

In [ ]:
Resultaat = pd.merge(Resultaat_2024, Resultaat_2023, on='Rubriek', suffixes=('_2024', '_2023'))
Resultaat = pd.merge(Resultaat, Resultaat_2022, on='Rubriek')
Resultaat.rename(columns={'Boekjaar':'Boekjaar_2022'}, inplace=True)
Resultaat.rename(columns={'Vorig_boekjaar':'Boekjaar_2021'}, inplace=True)
#Balans.drop_duplicates()
Resultaat

,Rubriek,Codes,Boekjaar_2024,Boekjaar_2023,Boekjaar_2022,Boekjaar_2021
0,Bedrijfsopbrengsten en bedrijfskosten,0,0,0,0,0
1,Brutomarge,9900,3.522.965,3.216.880,2.589.318,2.017.610
2,Waarvan: niet-recurrente bedrijfsopbrengsten,76A,152.259,149.950,95.300,18.761
3,Omzet,70,0,0,0,0
4,"Handelsgoederen, grond- en hulpstoffen, dienst...",0,0,0,0,0
...,...,...,...,...,...,...
76,Uit te keren winst,694/7,11.049,9.128,0,0
77,Vergoeding van de inbreng,694,0,0,0,0
78,Bestuurders of zaakvoerders,695,0,0,0,0
79,Werknemers,696,11.049,9.128,0,0
80,Andere rechthebbenden,697,0,0,0,0

In [ ]:
Balans.to_csv('Balans.csv', index=False)
Resultaat.to_csv('Resultaat.csv', index=False)

# Data verzameling

In [ ]:
df=Balans

# Eigen Vermogen & VASTE ACTIVA
## df.loc[df['Rubriek'] == 'Eigen Vermogen', t]

EV=df.loc[df['Codes'] == '10/15']
A = df.loc[df['Codes'] == '20/58']
P = df.loc[df['Codes'] == '10/49']

VA= df.loc[df['Codes'] == '21/28']
VLA = df.loc[df['Codes'] == '29/58']

VV = df.loc[df['Codes'] == '17/49']
VVLT =df.loc[df['Codes'] == '17']
VVKT = df.loc[df['Codes'] == '42/48']
VOORZIENINGEN = df.loc[df['Codes'] == '160/5']

Vordering_1j = df.loc[df['Codes'] == '40/41']

OVLR = df.loc[df['Codes'] == '490/1']
  # prompt: Dataframe OVLR gebruiken: Rename the Rubriek rows
  # Define the mapping from old Rubriek values to new Rubriek values
rubriek_rename_map = {
    'Overlopende rekeningen': 'Overlopende rekeningen A'
  }
  # Use the replace method to rename the values in the 'Rubriek' column
OVLR['Rubriek'] = OVLR['Rubriek'].replace(rubriek_rename_map)


Handelsschulden = df.loc[df['Codes'] == '44'] # < 1j
Overige_schulden = df.loc[df['Codes'] == '47/48'] # > 1j
OVLR_P = df.loc[df['Codes'] == '492/3']


df=Resultaat
#OMZET= df.loc[df['Codes'] == '70']
BM= df.loc[df['Codes'] == '9900'] # BM Bruto marge
WINST= df.loc[df['Codes'] == '9901']
WINST_voor_belasting= df.loc[df['Codes'] == '9903']


Afschrijvingen = df.loc[df['Codes'] == '630']
Afschrijvingen['Rubriek'] = 'Afschrijvingen'
Afschrijvingen = Afschrijvingen[(Afschrijvingen != 0).all(axis=1)]
Afschrijvingen


#Financiele opbrengsten en kosten
Financiele_opbrensten = df.loc[df['Codes'] == '75/76B']
Financiele_kosten = df.loc[df['Codes'] == '65/66B']


# Netto Financiele schuld
Geldbeleggingen = Balans.loc[Balans['Codes'] == '50/53']
Liquide_middelen =  Balans.loc[Balans['Codes'] == '54/58']
Financiele_schulden = Balans.loc[Balans['Codes'] == '170/4']

data = [EV, A, P, VA, VLA, OVLR, Vordering_1j,
        Handelsschulden, Overige_schulden, OVLR_P,
        VV, VVLT, VVKT, VOORZIENINGEN,
        BM, WINST, WINST_voor_belasting,
        Financiele_opbrensten, Financiele_kosten, Afschrijvingen,
        Geldbeleggingen, Liquide_middelen, Financiele_schulden
        ]

data = pd.concat(data)

# Drop rows overlopende rekening
data = data.drop(index=37)
data = data.drop(index=38)
data = data.drop(index=39)

data = data.drop(index=125)
data = data.drop(index=126)
data = data.drop(index=127)

# Drop rows overige schulden KT
data = data.drop(index=121)
data = data.drop(index=122)
data = data.drop(index=123)

# Drop rows Handelsschulden
data = data.drop(index=105)
data = data.drop(index=106)
data = data.drop(index=107)


# Drop rows Financieleschulden
data = data.drop(index=74)
data = data.drop(index=75)
data = data.drop(index=76)


data

<ipython-input-66-a06a92a6b83c>:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  OVLR['Rubriek'] = OVLR['Rubriek'].replace(rubriek_rename_map)
<ipython-input-66-a06a92a6b83c>:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Afschrijvingen['Rubriek'] = 'Afschrijvingen'

,Rubriek,Codes,Boekjaar_2024,Boekjaar_2023,Boekjaar_2022,Boekjaar_2021
42,EIGEN VERMOGEN,10/15,3.410.783,3.048.926,2.411.016,1.849.265
40,TOTAAL VAN DE ACTIVA,20/58,9.296.654,10.485.998,7.793.894,6.026.039
129,TOTAAL VAN DE PASSIVA,10/49,9.296.654,10.485.998,7.793.894,6.026.039
2,VASTE ACTIVA,21/28,7.744.716,8.560.679,6.337.109,4.770.730
12,VLOTTENDE ACTIVA,29/58,1.551.938,1.925.320,1.456.785,1.255.309
36,Overlopende rekeningen A,490/1,35.631,95.981,25.979,17.874
25,Vorderingen op ten hoogste één jaar,40/41,1.172.718,1.637.597,1.193.335,753.788
108,Handelsschulden,44,157.716,336.536,235.401,100.234
124,Overige schulden,47/48,57.553,3.756,0,0
128,Overlopende rekeningen,492/3,2.500,4.000,5.000,900
71,SCHULDEN,17/49,5.814.285,7.355.623,5.317.024,4.123.615
72,Schulden op meer dan één jaar,17,4.021.517,5.203.365,3.830.684,3.179.673
94,Schulden op ten hoogste één jaar,42/48,1.790.269,2.148.259,1.481.340,943.042
61,Voorzieningen voor risico's en kosten,160/5,0,0,0,0
1,Brutomarge,9900,3.522.965,3.216.880,2.589.318,2.017.610
44,Bedrijfswinst (Bedrijfsverlies),9901,628.497,783.233,692.701,353.953
52,Winst (Verlies) van het boekjaar vóór belasting,9903,486.107,684.959,608.034,276.804
45,Financiële opbrengsten,75/76B,1.618,400,6.600,5.600
49,Financiële kosten,65/66B,144.007,98.674,91.267,82.749
21,Afschrijvingen,630,1.007.836,800.103,599.986,653.964
34,Geldbeleggingen,50/53,225.866,75.000,0,0
35,Liquide middelen,54/58,117.722,116.741,237.471,483.647
73,Financiële schulden,170/4,4.021.517,5.203.365,3.830.684,3.179.673

In [ ]:
# prompt: Dataframe data gebruiken: convert columns Boekjaar_2024,  Boekjaar_2023, Boekjaar_2022 and Boekjaar_2021 in numeric columns

# List of columns to convert to numeric
columns_to_convert = ['Boekjaar_2024', 'Boekjaar_2023', 'Boekjaar_2022', 'Boekjaar_2021']
# Loop through the columns and convert them to numeric
for column in columns_to_convert:
    # Replace the dot '.' with an empty string to handle thousands separators
    data[column] = data[column].astype(str).str.replace('.', '', regex=False)
    # Convert the cleaned column to numeric, coercing errors to NaN
    data[column] = pd.to_numeric(data[column], errors='coerce')
    data

In [ ]:
df = data
df = df.drop('Codes', axis=1)
df = df.set_index('Rubriek')
df= df.transpose()
#data.rename(columns=data.iloc[0])
df.columns

Index(['EIGEN VERMOGEN', 'TOTAAL VAN DE ACTIVA', 'TOTAAL VAN DE PASSIVA',
       'VASTE ACTIVA', 'VLOTTENDE ACTIVA', 'Overlopende rekeningen A',
       'Vorderingen op ten hoogste één jaar', 'Handelsschulden',
       'Overige schulden', 'Overlopende rekeningen', 'SCHULDEN',
       'Schulden op meer dan één jaar', 'Schulden op ten hoogste één jaar',
       'Voorzieningen voor risico's en kosten', 'Brutomarge',
       'Bedrijfswinst (Bedrijfsverlies)',
       'Winst (Verlies) van het boekjaar vóór belasting',
       'Financiële opbrengsten', 'Financiële kosten', 'Afschrijvingen',
       'Geldbeleggingen', 'Liquide middelen', 'Financiële schulden'],
      dtype='object', name='Rubriek')

In [ ]:
# Ratios
df['Liquiditeit'] = df['VLOTTENDE ACTIVA'] / df['Schulden op ten hoogste één jaar']
df['Acid_test'] = df['Vorderingen op ten hoogste één jaar'] / df['Schulden op ten hoogste één jaar'] + df['Overlopende rekeningen A'] / df['Schulden op ten hoogste één jaar']

#Solvabiliteit VV P (totaal vermogen)
df['Solvabiliteit_S'] = df['EIGEN VERMOGEN'] / df['SCHULDEN']
df['Solvabiliteit_A'] = df['EIGEN VERMOGEN'] / df['TOTAAL VAN DE ACTIVA']
df['Solvabiliteit_LT'] = df['EIGEN VERMOGEN'] / df['Schulden op meer dan één jaar']




# NA, NBA, NBK
df['Netto Actief'] = df['TOTAAL VAN DE ACTIVA'] - df['SCHULDEN'] - df["Voorzieningen voor risico's en kosten"] # Boekhoudkundig eigen vermogen
df['NBA'] = df['Vorderingen op ten hoogste één jaar'] + df['Overlopende rekeningen A'] - df["Handelsschulden"] - df["Overlopende rekeningen"]# NBA Netto Bedrijfsactiva, Vermogensstructuur op lange termijn + Winstgevendheid & waardering

df['Bedrijfs Activa'] = df['Vorderingen op ten hoogste één jaar'] + df['Overlopende rekeningen A']
df['Bedrijfs Passiva'] = df["Handelsschulden"] + df["Overlopende rekeningen"]

df['NBK'] = df['EIGEN VERMOGEN'] +  df['Schulden op meer dan één jaar'] - df["VASTE ACTIVA"]
df['NBK_1'] = df['VLOTTENDE ACTIVA']  - df["Schulden op ten hoogste één jaar"]

df['Nettokas'] = df['NBK']  - df["NBA"]


# EBIT
df['EBIT'] = df['Bedrijfswinst (Bedrijfsverlies)']  + df["Financiële opbrengsten"] - df["Financiële kosten"]
df['EBITDA'] = df['EBIT'] + df['Afschrijvingen']




# Financiële Schuld
df['Netto Financiele schuld'] = df['Financiële schulden']  - df["Geldbeleggingen"] - df["Liquide middelen"]
df['Netto Financiele schuldsgraad'] = df['Netto Financiele schuld'] / df['EIGEN VERMOGEN']
df['Netto Financiele schuld ratio'] = df['Netto Financiele schuld'] / df['EBITDA']

# Intrestdekking
df['Intrestdekking'] = df['Winst (Verlies) van het boekjaar vóór belasting'] / df['Financiële kosten'] - 1

# Schuldaflossingscapaciteit
df['Schuldaflossingscapaciteit'] = df['Netto Financiele schuld'] / df['EBITDA']

# Rentabiliteit op basis van de EV of P
df['Rentabiliteit_EV'] = df['Bedrijfswinst (Bedrijfsverlies)'] / df['EIGEN VERMOGEN']
df['Rentabiliteit_P'] = df['Bedrijfswinst (Bedrijfsverlies)'] / df['TOTAAL VAN DE PASSIVA']

#Financiele hefboom (Veel schuld → meer risico en potentieel hoger rendement)
df['Financiele_hefboom'] = df['SCHULDEN'] / df['EIGEN VERMOGEN'] # VV/EV = (R/VV)/(R/EV)
df['Financiele_hefboom_1'] = df['TOTAAL VAN DE ACTIVA'] / df['EIGEN VERMOGEN'] # VV/EV = (R/VV)/(R/EV)
df

df

Rubriek,EIGEN VERMOGEN,TOTAAL VAN DE ACTIVA,TOTAAL VAN DE PASSIVA,VASTE ACTIVA,VLOTTENDE ACTIVA,Overlopende rekeningen A,Vorderingen op ten hoogste één jaar,Handelsschulden,Overige schulden,Overlopende rekeningen,...,EBITDA,Netto Financiele schuld,Netto Financiele schuldsgraad,Netto Financiele schuld ratio,Intrestdekking,Schuldaflossingscapaciteit,Rentabiliteit_EV,Rentabiliteit_P,Financiele_hefboom,Financiele_hefboom_1
Boekjaar_2024,3410783,9296654,9296654,7744716,1551938,35631,1172718,157716,57553,2500,...,1493944,3677929,1.078324,2.461892,2.375579,2.461892,0.184268,0.067605,1.704677,2.725666
Boekjaar_2023,3048926,10485998,10485998,8560679,1925320,95981,1637597,336536,3756,4000,...,1485062,5011624,1.643734,3.374690,5.941636,3.374690,0.256888,0.074693,2.412529,3.439243
Boekjaar_2022,2411016,7793894,7793894,6337109,1456785,25979,1193335,235401,0,5000,...,1208020,3593213,1.490331,2.974465,5.662145,2.974465,0.287307,0.088877,2.205304,3.232618
Boekjaar_2021,1849265,6026039,6026039,4770730,1255309,17874,753788,100234,0,900,...,930768,2696026,1.457891,2.896561,2.345104,2.896561,0.191402,0.058737,2.229867,3.258613

In [ ]:
df= df.transpose()
df

,Boekjaar_2024,Boekjaar_2023,Boekjaar_2022,Boekjaar_2021
Rubriek,,,,
EIGEN VERMOGEN,3.410783e+06,3.048926e+06,2.411016e+06,1.849265e+06
TOTAAL VAN DE ACTIVA,9.296654e+06,1.048600e+07,7.793894e+06,6.026039e+06
TOTAAL VAN DE PASSIVA,9.296654e+06,1.048600e+07,7.793894e+06,6.026039e+06
VASTE ACTIVA,7.744716e+06,8.560679e+06,6.337109e+06,4.770730e+06
VLOTTENDE ACTIVA,1.551938e+06,1.925320e+06,1.456785e+06,1.255309e+06
Overlopende rekeningen A,3.563100e+04,9.598100e+04,2.597900e+04,1.787400e+04
Vorderingen op ten hoogste één jaar,1.172718e+06,1.637597e+06,1.193335e+06,7.537880e+05
Handelsschulden,1.577160e+05,3.365360e+05,2.354010e+05,1.002340e+05
Overige schulden,5.755300e+04,3.756000e+03,0.000000e+00,0.000000e+00
Overlopende rekeningen,2.500000e+03,4.000000e+03,5.000000e+03,9.000000e+02
SCHULDEN,5.814285e+06,7.355623e+06,5.317024e+06,4.123615e+06
Schulden op meer dan één jaar,4.021517e+06,5.203365e+06,3.830684e+06,3.179673e+06
Schulden op ten hoogste één jaar,1.790269e+06,2.148259e+06,1.481340e+06,9.430420e+05
Voorzieningen voor risico's en kosten,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Brutomarge,3.522965e+06,3.216880e+06,2.589318e+06,2.017610e+06
Bedrijfswinst (Bedrijfsverlies),6.284970e+05,7.832330e+05,6.927010e+05,3.539530e+05
Winst (Verlies) van het boekjaar vóór belasting,4.861070e+05,6.849590e+05,6.080340e+05,2.768040e+05
Financiële opbrengsten,1.618000e+03,4.000000e+02,6.600000e+03,5.600000e+03
Financiële kosten,1.440070e+05,9.867400e+04,9.126700e+04,8.274900e+04
Afschrijvingen,1.007836e+06,8.001030e+05,5.999860e+05,6.539640e+05
Geldbeleggingen,2.258660e+05,7.500000e+04,0.000000e+00,0.000000e+00
Liquide middelen,1.177220e+05,1.167410e+05,2.374710e+05,4.836470e+05
Financiële schulden,4.021517e+06,5.203365e+06,3.830684e+06,3.179673e+06
Liquiditeit,8.668742e-01,8.962234e-01,9.834238e-01,1.331127e+00
Acid_test,6.749539e-01,8.069688e-01,8.231156e-01,8.182690e-01
Solvabiliteit_S,5.866212e-01,4.145028e-01,4.534522e-01,4.484572e-01
Solvabiliteit_A,3.668829e-01,2.907616e-01,3.093468e-01,3.068790e-01
Solvabiliteit_LT,8.481334e-01,5.859527e-01,6.293957e-01,5.815897e-01
Netto Actief,3.482369e+06,3.130375e+06,2.476870e+06,1.902424e+06
NBA,1.048133e+06,1.393042e+06,9.789130e+05,6.705280e+05
Bedrijfs Activa,1.208349e+06,1.733578e+06,1.219314e+06,7.716620e+05
Bedrijfs Passiva,1.602160e+05,3.405360e+05,2.404010e+05,1.011340e+05
NBK,-3.124160e+05,-3.083880e+05,-9.540900e+04,2.582080e+05
NBK_1,-2.383310e+05,-2.229390e+05,-2.455500e+04,3.122670e+05
Nettokas,-1.360549e+06,-1.701430e+06,-1.074322e+06,-4.123200e+05
EBIT,4.861080e+05,6.849590e+05,6.080340e+05,2.768040e+05
EBITDA,1.493944e+06,1.485062e+06,1.208020e+06,9.307680e+05
Netto Financiele schuld,3.677929e+06,5.011624e+06,3.593213e+06,2.696026e+06
Netto Financiele schuldsgraad,1.078324e+00,1.643734e+00,1.490331e+00,1.457891e+00
Netto Financiele schuld ratio,2.461892e+00,3.374690e+00,2.974465e+00,2.896561e+00
Intrestdekking,2.375579e+00,5.941636e+00,5.662145e+00,2.345104e+00
Schuldaflossingscapaciteit,2.461892e+00,3.374690e+00,2.974465e+00,2.896561e+00
Rentabiliteit_EV,1.842677e-01,2.568882e-01,2.873067e-01,1.914020e-01
Rentabiliteit_P,6.760465e-02,7.469322e-02,8.887740e-02,5.873726e-02
Financiele_hefboom,1.704677e+00,2.412529e+00,2.205304e+00,2.229867e+00
Financiele_hefboom_1,2.725666e+00,3.439243e+00,3.232618e+00,3.258613e+00

In [ ]:
df.to_csv('Ratios.csv', index=False)

In [ ]:
print(df.to_latex(index=False, formatters={"name": str.upper}, float_format="{:.2f}".format))

In [ ]:
# prompt: Ik wil df as een tabel voor Latex met de index kolum

print(df.to_latex(index=True, formatters={"name": str.upper}, float_format="{:.2f}".format))

\begin{tabular}{lrrrr}
\toprule
 & Boekjaar_2024 & Boekjaar_2023 & Boekjaar_2022 & Boekjaar_2021 \\
Rubriek &  &  &  &  \\
\midrule
EIGEN VERMOGEN & 3410783.00 & 3048926.00 & 2411016.00 & 1849265.00 \\
TOTAAL VAN DE ACTIVA & 9296654.00 & 10485998.00 & 7793894.00 & 6026039.00 \\
TOTAAL VAN DE PASSIVA & 9296654.00 & 10485998.00 & 7793894.00 & 6026039.00 \\
VASTE ACTIVA & 7744716.00 & 8560679.00 & 6337109.00 & 4770730.00 \\
VLOTTENDE ACTIVA & 1551938.00 & 1925320.00 & 1456785.00 & 1255309.00 \\
Overlopende rekeningen A & 35631.00 & 95981.00 & 25979.00 & 17874.00 \\
Vorderingen op ten hoogste één jaar & 1172718.00 & 1637597.00 & 1193335.00 & 753788.00 \\
Handelsschulden & 157716.00 & 336536.00 & 235401.00 & 100234.00 \\
Overige schulden & 57553.00 & 3756.00 & 0.00 & 0.00 \\
Overlopende rekeningen & 2500.00 & 4000.00 & 5000.00 & 900.00 \\
SCHULDEN & 5814285.00 & 7355623.00 & 5317024.00 & 4123615.00 \\
Schulden op meer dan één jaar & 4021517.00 & 5203365.00 & 3830684.00 & 3179673.00 \\
Schulden op ten hoogste één jaar & 1790269.00 & 2148259.00 & 1481340.00 & 943042.00 \\
Voorzieningen voor risico's en kosten & 0.00 & 0.00 & 0.00 & 0.00 \\
Brutomarge & 3522965.00 & 3216880.00 & 2589318.00 & 2017610.00 \\
Bedrijfswinst (Bedrijfsverlies) & 628497.00 & 783233.00 & 692701.00 & 353953.00 \\
Winst (Verlies) van het boekjaar vóór belasting & 486107.00 & 684959.00 & 608034.00 & 276804.00 \\
Financiële opbrengsten & 1618.00 & 400.00 & 6600.00 & 5600.00 \\
Financiële kosten & 144007.00 & 98674.00 & 91267.00 & 82749.00 \\
Afschrijvingen & 1007836.00 & 800103.00 & 599986.00 & 653964.00 \\
Geldbeleggingen & 225866.00 & 75000.00 & 0.00 & 0.00 \\
Liquide middelen & 117722.00 & 116741.00 & 237471.00 & 483647.00 \\
Financiële schulden & 4021517.00 & 5203365.00 & 3830684.00 & 3179673.00 \\
Liquiditeit & 0.87 & 0.90 & 0.98 & 1.33 \\
Acid_test & 0.67 & 0.81 & 0.82 & 0.82 \\
Solvabiliteit_S & 0.59 & 0.41 & 0.45 & 0.45 \\
Solvabiliteit_A & 0.37 & 0.29 & 0.31 & 0.31 \\
Solvabiliteit_LT & 0.85 & 0.59 & 0.63 & 0.58 \\
Netto Actief & 3482369.00 & 3130375.00 & 2476870.00 & 1902424.00 \\
NBA & 1048133.00 & 1393042.00 & 978913.00 & 670528.00 \\
Bedrijfs Activa & 1208349.00 & 1733578.00 & 1219314.00 & 771662.00 \\
Bedrijfs Passiva & 160216.00 & 340536.00 & 240401.00 & 101134.00 \\
NBK & -312416.00 & -308388.00 & -95409.00 & 258208.00 \\
NBK_1 & -238331.00 & -222939.00 & -24555.00 & 312267.00 \\
Nettokas & -1360549.00 & -1701430.00 & -1074322.00 & -412320.00 \\
EBIT & 486108.00 & 684959.00 & 608034.00 & 276804.00 \\
EBITDA & 1493944.00 & 1485062.00 & 1208020.00 & 930768.00 \\
Netto Financiele schuld & 3677929.00 & 5011624.00 & 3593213.00 & 2696026.00 \\
Netto Financiele schuldsgraad & 1.08 & 1.64 & 1.49 & 1.46 \\
Netto Financiele schuld ratio & 2.46 & 3.37 & 2.97 & 2.90 \\
Intrestdekking & 2.38 & 5.94 & 5.66 & 2.35 \\
Schuldaflossingscapaciteit & 2.46 & 3.37 & 2.97 & 2.90 \\
Rentabiliteit_EV & 0.18 & 0.26 & 0.29 & 0.19 \\
Rentabiliteit_P & 0.07 & 0.07 & 0.09 & 0.06 \\
Financiele_hefboom & 1.70 & 2.41 & 2.21 & 2.23 \\
Financiele_hefboom_1 & 2.73 & 3.44 & 3.23 & 3.26 \\
\bottomrule
\end{tabular}

In [ ]:
# prompt: Delete all rows with zero

df = df[(df != 0).all(axis=1)]
df